language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode10.1
      compiler: clang

script:
  - cmake -H. -Bbuild
  - cmake --build build
